exec-once = awww-daemon
exec-once = bash -c "sleep 5 && awww img /usr/share/churros/wallpapers/default.png --transition-type none"

exec-once = /usr/bin/waybar --config /home/churros/.config/waybar/config.jsonc
exec-once = churros-welcome