---
backend: pacman

skip_if_no_internet: false
update_db: true
update_system: false

pacman:
  num_retries: 0
  disable_download_timeout: false
  needed_only: false

operations:
  - try_remove:
      - archinstall
      - clonezilla
      - gpm
      - irssi
      - lynx
      - mc
      - testdisk
      - wvdial
