---
efiSystemPartition: "/boot/efi"

userSwapChoices:
  - none
  - small
  - suspend
  - file

# defaultPartitionTableType: gpt
defaultFileSystemType: "btrfs"
availableFileSystemTypes:
  - btrfs
  - ext4
# Choose a layout for the firmware mode used to boot the installer. A hybrid
# BIOS + EFI layout is unnecessary here and can create extra partitions.
createHybridBootloaderLayout: true

allowManualPartitioning: true
