---
efiSystemPartition: "/boot/efi"

userSwapChoices:
  - none
  - small
  - suspend
  - file

defaultPartitionTableType: gpt
defaultFileSystemType: "btrfs"
availableFileSystemTypes:
  - btrfs
  - ext4
createHybridBootloaderLayout: true

allowManualPartitioning: true
