---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  - name: "systemd-resolved.service"
    action: "enable"
    mandatory: true
  - name: "iwd.service"
    action: "disable"
    mandatory: false
  - name: "systemd-networkd.service"
    action: "disable"
    mandatory: false
  - name: "systemd-networkd.socket"
    action: "disable"
    mandatory: false
  - name: "systemd-networkd-wait-online.service"
    action: "disable"
    mandatory: false
  - name: "hv_fcopy_daemon.service"
    action: "disable"
    mandatory: false
  - name: "hv_kvp_daemon.service"
    action: "disable"
    mandatory: false
  - name: "hv_vss_daemon.service"
    action: "disable"
    mandatory: false
  - name: "vboxservice.service"
    action: "disable"
    mandatory: false
  - name: "vmtoolsd.service"
    action: "disable"
    mandatory: false
  - name: "vmware-vmblock-fuse.service"
    action: "disable"
    mandatory: false
  - name: "greetd.service"
    action: "enable"
    mandatory: true
  - name: "ufw.service"
    action: "enable"
    mandatory: false
  - name: "bluetooth.service"
    action: "enable"
    mandatory: false
  - name: "graphical.target"
    action: "enable"
    mandatory: true
  - name: "pacman-init.service"
    action: "mask"
  - name: "choose-mirror.service"
    action: "mask"
  - name: "getty@tty1.service"
    action: "mask"
    mandatory: false
  - name: "livecd-talk.service"
    action: "mask"
    mandatory: false
