---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  - name: "sddm.service"
    action: "enable"
    mandatory: true
  - name: "bluetooth.service"
    action: "enable"
    mandatory: false
  - name: "graphical.target"
    action: "enable"
    mandatory: true
  - name: "pacman-init.service"
    action: "mask"
  - name: "choose-mirror.service"
    action: "mask"
  - name: "livecd-talk.service"
    action: "mask"
    mandatory: false
