---
dontChroot: false
timeout: 30
verbose: true

script:
  - "-rm -r /etc/mkinitcpio.conf.d/"
  - "rm -f /etc/mkinitcpio.conf.d/archiso.conf"
  - "sed -i \"s/PRESETS=('archiso')/PRESETS=('default')/\" /etc/mkinitcpio.d/linux.preset"
  - "sed -i 's|archiso_config=.*|default_config=\"/etc/mkinitcpio.conf\"|' /etc/mkinitcpio.d/linux.preset"
  - "sed -i 's|archiso_image=|default_image=|' /etc/mkinitcpio.d/linux.preset"
