---
dontChroot: false
timeout: 60
verbose: true

script:
  - "mkdir -p /boot/grub/themes/churros"
  - "cp -r /usr/share/churros/grub-theme/. /boot/grub/themes/churros/"
  - "grep -q '^GRUB_THEME=' /etc/default/grub || echo 'GRUB_THEME=\"/boot/grub/themes/churros/theme.txt\"' >> /etc/default/grub"
  - "grub-mkconfig -o /boot/grub/grub.cfg"
  - "/usr/share/churros/scripts/make-boot-grub-readable"