---
dontChroot: false
timeout: 30
verbose: true

script:
  - command: 'ln -sf $(ls -d /usr/lib/modules/*/vmlinuz | head -1) /boot/vmlinuz-linux'
    timeout: 5
  - command: 'rm -f /etc/mkinitcpio.conf.d/archiso.conf'
    timeout: 5
  - command: 'printf "ALL_config=\"/etc/mkinitcpio.conf\"\nALL_kver=\"/boot/vmlinuz-linux\"\n\nPRESETS=(\"default\" \"fallback\")\n\n[default]\nimage=\"/boot/initramfs-linux.img\"\n\n[fallback]\nimage=\"/boot/initramfs-linux-fallback.img\"\noptions=\"-S autodetect\"\n" > /etc/mkinitcpio.d/linux.preset'
    timeout: 10
