---
dontChroot: false
timeout: 120
verbose: false

script:
  - command: "pacman-key --init"
    timeout: 120
  - command: "pacman-key --populate archlinuxarm"
    timeout: 120
  - command: "-pacman -Sy --noconfirm"
    timeout: 120
