---
dontChroot: false
timeout: 30
verbose: false

script:
  - command: "rm -rf /var/cache/pacman/pkg/*"
    timeout: 30
  - command: "rm -f /etc/sudoers.d/churros"
    timeout: 5
  - command: "echo 'ChurrOS instalado correctamente.' > /etc/motd"
    timeout: 5
  - command: "rm -rf /usr/bin/calamares /usr/lib/calamares /usr/share/calamares /usr/share/applications/calamares.desktop /etc/calamares"
    timeout: 10
  - command: "rm -f /usr/share/polkit-1/actions/io.calamares.calamares.policy /usr/share/polkit-1/rules.d/49-calamares.rules /etc/polkit-1/rules.d/49-calamares.rules"
    timeout: 5
  - command: "rm -rf /usr/include/libcalamares"
    timeout: 5
  - command: "bash /root/scripts/greetd-config.sh"
    timeout: 5
  - command: "rm -rf /etc/sddm.conf.d"
    timeout: 5
