---
dontChroot: false
timeout: 120
verbose: false

script:
  - command: |
      if ! grep -q '^\[churros\]$' /etc/pacman.conf; then
        printf '\n[churros]\nSigLevel = Optional TrustAll\nServer = file:///root/packages\n' >> /etc/pacman.conf
      fi
    timeout: 10
  - command: "pacman -Sy --noconfirm"
    timeout: 120
