---
unpack:
  - source: "/run/archiso/bootmnt/churros/aarch64/airootfs.sfs"
    sourcefs: "squashfs"
    destination: ""
    weight: 12
  - source: "/run/archiso/bootmnt/churros/boot/aarch64/vmlinuz-linux-aarch64"
    sourcefs: "file"
    destination: "/boot/vmlinuz-linux-aarch64"
  - source: "/run/archiso/bootmnt/churros/boot/aarch64/initramfs-linux-aarch64.img"
    sourcefs: "file"
    destination: "/boot/initramfs-linux-aarch64.img"
