[main]
font=JetBrainsMono Nerd Font:size=10
dpi-aware=yes
pad=8x8
shell=zsh
term=xterm-256color
bold-text-in-bright=yes

[cursor]
style=beam
blink=yes
beam-thickness=2
#color=cbc5c4

[colors-dark]
foreground=cbc5c4
background=2f1914
regular0=2f1914
regular1=BC8960
regular2=B19C8D
regular3=CEAE98
regular4=D8C7B4
regular5=FCD0AE
regular6=E9D9CF
regular7=cbc5c4
bright0=796763
bright1=BC8960
bright2=B19C8D
bright3=CEAE98
bright4=D8C7B4
bright5=FCD0AE
bright6=E9D9CF
bright7=cbc5c4

[mouse]
hide-when-typing=yes

[bell]
urgent=yes
notify=yes
