foreground         #cbc5c4
background         #2f1914
background_opacity 1.0
cursor             #cbc5c4

active_tab_foreground     #2f1914
active_tab_background     #cbc5c4
inactive_tab_foreground   #cbc5c4
inactive_tab_background   #2f1914

active_border_color   #cbc5c4
inactive_border_color #2f1914
bell_border_color     #BC8960

color0       #2f1914
color8       #796763
color1       #BC8960
color9       #BC8960
color2       #B19C8D
color10      #B19C8D
color3       #CEAE98
color11      #CEAE98
color4       #D8C7B4
color12      #D8C7B4
color5       #FCD0AE
color13      #FCD0AE
color6       #E9D9CF
color14      #E9D9CF
color7       #cbc5c4
color15      #cbc5c4
