# fuzzel — glassmorphism + futurist

[main]
font=JetBrainsMono Nerd Font:size=13:weight=medium
dpi-aware=yes
layer=overlay
anchor=center
width=48
lines=12
horizontal-pad=36
vertical-pad=14
inner-pad=4
line-height=24
letter-spacing=1
hide-before-typing=no
exit-on-keyboard-focus-loss=yes

[colors]
background=2a161288
text=c9c4c3ff
match=D7C7B5ff
selection=D7C7B533
selection-text=c9c4c3ff
selection-match=BDA798ff
border=D7C7B5aa
prompt=E7D6CBff
placeholder=76656188
input=c9c4c3ff
message=766561cc
counter=76656188

[border]
width=2
radius=0
selection-radius=0

[dmenu]
mode=text
