---
modules-search:
  - local

instances:
  - id: pacman-init
    module: shellprocess
    config: shellprocess-pacman.conf
  - id: fix-boot
    module: shellprocess
    config: shellprocess-fixboot.conf
  - id: post-install
    module: shellprocess
    config: shellprocess-cleanup.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - netinstall
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - shellprocess@pacman-init
      - shellprocess@fix-boot
      - netinstall
      - packages
      - initcpiocfg
      - initcpio
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - grubcfg
      - bootloader
      - shellprocess@post-install
      - umount
  - show:
      - finished

branding: churros

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
