// ==========================================
// AccentService — genera ~/.config/churros/accent.css
// (equivalente a services/accent.py)
// ==========================================

use std::fs;
use std::path::PathBuf;

use crate::services::settings;

pub struct AccentService;

impl AccentService {
    pub const COLORS: [(&'static str, &'static str); 8] = [
        ("Blue", "#3584E4"),
        ("Purple", "#9141AC"),
        ("Pink", "#E01B9C"),
        ("Red", "#E62D2D"),
        ("Orange", "#E66100"),
        ("Yellow", "#F5C211"),
        ("Green", "#2EC27E"),
        ("Teal", "#1C71D8"),
    ];

    pub fn accent_css_path() -> PathBuf {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
        PathBuf::from(home).join(".config").join("churros").join("accent.css")
    }

    pub fn current() -> String {
        settings::get_string("accent.color", "Blue")
    }

    pub fn hex_for(name: &str) -> String {
        Self::COLORS
            .iter()
            .find(|(n, _)| *n == name)
            .map(|(_, h)| h.to_string())
            .unwrap_or_else(|| Self::COLORS[4].1.to_string()) // Orange por defecto
    }

    // Convierte #rrggbb a HLS y ajusta luminosidad/saturación (como colorsys)
    fn adjust(hex: &str, light_delta: f64, sat_delta: f64) -> String {
        let hex = hex.trim_start_matches('#');
        let r = u8::from_str_radix(&hex[0..2], 16).unwrap_or(0) as f64 / 255.0;
        let g = u8::from_str_radix(&hex[2..4], 16).unwrap_or(0) as f64 / 255.0;
        let b = u8::from_str_radix(&hex[4..6], 16).unwrap_or(0) as f64 / 255.0;

        let max = r.max(g).max(b);
        let min = r.min(g).min(b);
        let l = (max + min) / 2.0;

        let (h, s) = if max == min {
            (0.0, 0.0)
        } else {
            let d = max - min;
            let s = if l > 0.5 { d / (2.0 - max - min) } else { d / (max + min) };
            let h = if max == r {
                (g - b) / d + if g < b { 6.0 } else { 0.0 }
            } else if max == g {
                (b - r) / d + 2.0
            } else {
                (r - g) / d + 4.0
            };
            (h / 6.0, s)
        };

        let l = (l + light_delta).clamp(0.0, 1.0);
        let s = (s + sat_delta).clamp(0.0, 1.0);

        // HLS -> RGB (colorsys.hls_to_rgb)
        let rgb = hls_to_rgb(h, l, s);

        format!("#{:02x}{:02x}{:02x}", rgb.0, rgb.1, rgb.2)
    }

    fn build_accent_css(base: &str, source: &str) -> String {
        let strong = Self::adjust(base, -0.08, 0.0);
        let soft = Self::adjust(base, 0.18, 0.0);
        let hover = Self::adjust(base, 0.32, 0.0);
        let glow = Self::adjust(base, 0.0, 0.0);

        format!(
            "/* Auto-generated by {source}. Do not edit. */\n\
             window {{\n\
                 --accent: {base};\n\
                 --accent-strong: {strong};\n\
                 --accent-soft: {soft};\n\
                 --accent-text: #ffffff;\n\
                 --accent-bg-hover: {hover};\n\
                 --accent-glow: 0 0 20px {glow}40;\n\
             }}\n"
        )
    }

    fn write_accent_css(color_name: &str) {
        let path = Self::accent_css_path();
        if let Some(parent) = path.parent() {
            let _ = fs::create_dir_all(parent);
        }
        let base = Self::hex_for(color_name);
        let _ = fs::write(path, Self::build_accent_css(&base, "churros set-accent"));
    }

    pub fn set(color: &str) {
        settings::set("accent.color", serde_json::json!(color));
        Self::write_accent_css(color);
        // Si pywal está activo, el color con nombre se sobrescribe por la
        // paleta dinámica (paridad con accent.py del Python).
        if crate::services::pywal::PywalService::enabled() {
            if let Some(palette) = crate::services::pywal::PywalService::generate() {
                crate::services::pywal::PywalService::apply_accent(&palette);
            }
        }
    }

    /// Escribe accent.css con un hex arbitrario (para pywal). NO persiste en
    /// settings.json: el color custom se sobrescribe la próxima vez que el
    /// usuario elige un color con nombre.
    pub fn set_hex(hex: &str) {
        let base = if hex.starts_with('#') {
            hex.to_string()
        } else {
            format!("#{hex}")
        };
        let path = Self::accent_css_path();
        if let Some(parent) = path.parent() {
            let _ = fs::create_dir_all(parent);
        }
        let _ = fs::write(
            path,
            Self::build_accent_css(&base, "dynamic colors (pywal)"),
        );
    }

    pub fn ensure() {
        let color = Self::current();
        if !Self::accent_css_path().exists() {
            Self::write_accent_css(&color);
        }
    }
}

fn hls_to_rgb(h: f64, l: f64, s: f64) -> (u8, u8, u8) {
    if s == 0.0 {
        let v = (l * 255.0).round() as u8;
        return (v, v, v);
    }
    let q = if l < 0.5 { l * (1.0 + s) } else { l + s - l * s };
    let p = 2.0 * l - q;
    let rgb = [
        hue_to_rgb(p, q, h + 1.0 / 3.0),
        hue_to_rgb(p, q, h),
        hue_to_rgb(p, q, h - 1.0 / 3.0),
    ];
    (
        (rgb[0] * 255.0).round() as u8,
        (rgb[1] * 255.0).round() as u8,
        (rgb[2] * 255.0).round() as u8,
    )
}

fn hue_to_rgb(p: f64, q: f64, mut t: f64) -> f64 {
    if t < 0.0 {
        t += 1.0;
    }
    if t > 1.0 {
        t -= 1.0;
    }
    if t < 1.0 / 6.0 {
        p + (q - p) * 6.0 * t
    } else if t < 1.0 / 2.0 {
        q
    } else if t < 2.0 / 3.0 {
        p + (q - p) * (2.0 / 3.0 - t) * 6.0
    } else {
        p
    }
}
