// ==========================================
// AccentService — genera ~/.config/churros/accent.css
// (equivalente a services/accent.py)
// ==========================================

use std::cell::RefCell;
use std::fs;
use std::path::PathBuf;

use gtk::prelude::*;
use gtk::gdk;

use crate::services::settings;

thread_local! {
    static ACCENT_PROVIDER: RefCell<Option<gtk::CssProvider>> = const { RefCell::new(None) };
}

pub struct AccentService;

impl AccentService {
    pub const COLORS: [(&'static str, &'static str); 8] = [
        ("Blue", "#3584E4"),
        ("Purple", "#9141AC"),
        ("Pink", "#E01B9C"),
        ("Red", "#E62D2D"),
        ("Orange", "#E66100"),
        ("Yellow", "#F5C211"),
        ("Green", "#2EC27E"),
        ("Teal", "#1C71D8"),
    ];

    pub fn accent_css_path() -> PathBuf {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
        PathBuf::from(home).join(".config").join("churros").join("accent.css")
    }

    pub fn current() -> String {
        settings::get_string("accent.color", "Blue")
    }

    pub fn hex_for(name: &str) -> String {
        Self::COLORS
            .iter()
            .find(|(n, _)| *n == name)
            .map(|(_, h)| h.to_string())
            .unwrap_or_else(|| Self::COLORS[0].1.to_string()) // Blue por defecto
    }

    // Convierte #rrggbb a HLS y ajusta luminosidad/saturación (como colorsys)
    fn adjust(hex: &str, light_delta: f64, sat_delta: f64) -> String {
        let hex = hex.trim_start_matches('#');
        if hex.len() < 6 {
            return "#38BDF8".to_string();
        }
        let r = u8::from_str_radix(&hex[0..2], 16).unwrap_or(0) as f64 / 255.0;
        let g = u8::from_str_radix(&hex[2..4], 16).unwrap_or(0) as f64 / 255.0;
        let b = u8::from_str_radix(&hex[4..6], 16).unwrap_or(0) as f64 / 255.0;

        let max = r.max(g).max(b);
        let min = r.min(g).min(b);
        let l = (max + min) / 2.0;

        let (h, s) = if max == min {
            (0.0, 0.0)
        } else {
            let d = max - min;
            let s = if l > 0.5 { d / (2.0 - max - min) } else { d / (max + min) };
            let h = if max == r {
                (g - b) / d + if g < b { 6.0 } else { 0.0 }
            } else if max == g {
                (b - r) / d + 2.0
            } else {
                (r - g) / d + 4.0
            };
            (h / 6.0, s)
        };

        let l = (l + light_delta).clamp(0.0, 1.0);
        let s = (s + sat_delta).clamp(0.0, 1.0);

        // HLS -> RGB (colorsys.hls_to_rgb)
        let rgb = hls_to_rgb(h, l, s);

        format!("#{:02x}{:02x}{:02x}", rgb.0, rgb.1, rgb.2)
    }

    fn hex_to_rgba(hex: &str, alpha: f64) -> String {
        let hex = hex.trim_start_matches('#');
        if hex.len() < 6 {
            return format!("rgba(56, 189, 248, {alpha})");
        }
        let r = u8::from_str_radix(&hex[0..2], 16).unwrap_or(56);
        let g = u8::from_str_radix(&hex[2..4], 16).unwrap_or(189);
        let b = u8::from_str_radix(&hex[4..6], 16).unwrap_or(248);
        format!("rgba({r}, {g}, {b}, {alpha})")
    }

    fn build_accent_css(base: &str, source: &str) -> String {
        let strong = Self::adjust(base, -0.08, 0.0);
        let soft = Self::adjust(base, 0.18, 0.0);
        let hover = Self::hex_to_rgba(base, 0.14);
        let glow = Self::hex_to_rgba(base, 0.25);

        format!(
            "/* Auto-generated by {source}. Do not edit. */\n\
             window, window.dark, window.light, .preferences, .welcome, .control-center, .popup, popover, dialog {{\n\
                 --accent: {base};\n\
                 --accent-strong: {strong};\n\
                 --accent-soft: {soft};\n\
                 --accent-text: #ffffff;\n\
                 --accent-bg-hover: {hover};\n\
                 --accent-glow: 0 0 20px {glow};\n\
             }}\n"
        )
    }

    /// Inicializa el CssProvider singleton para accent.css y lo registra
    /// una única vez en el Display con prioridad USER.
    pub fn init_css_provider() {
        let provider = gtk::CssProvider::new();
        let path = Self::accent_css_path();
        let css = if path.exists() {
            fs::read_to_string(&path).unwrap_or_else(|_| {
                let base = Self::hex_for(&Self::current());
                Self::build_accent_css(&base, "churros set-accent")
            })
        } else {
            let base = Self::hex_for(&Self::current());
            Self::build_accent_css(&base, "churros set-accent")
        };
        provider.connect_parsing_error(|_, _, err| {
            crate::logging::log(&format!("[accent-css] init parse error: {err}"));
        });
        provider.load_from_string(&css);

        if let Some(display) = gdk::Display::default() {
            gtk::style_context_add_provider_for_display(
                &display,
                &provider,
                gtk::STYLE_PROVIDER_PRIORITY_USER,
            );
        }

        ACCENT_PROVIDER.with(|p| {
            *p.borrow_mut() = Some(provider);
        });
    }

    /// Reemplaza el CssProvider atómicamente en la Display: crea uno nuevo,
    /// lo parsea fuera de la Display, lo añade y luego retira el anterior.
    /// Esto evita la invalidación destructiva in-place de load_from_data
    /// que causaba aserciones fallidas de estilo en GTK4/Libadwaita.
    fn apply_css_to_provider(css: &str) {
        if let Some(display) = gdk::Display::default() {
            let new_provider = gtk::CssProvider::new();
            new_provider.connect_parsing_error(|_, _, err| {
                crate::logging::log(&format!("[accent-css] reload parse error: {err}"));
            });
            new_provider.load_from_string(css);
            gtk::style_context_add_provider_for_display(
                &display,
                &new_provider,
                gtk::STYLE_PROVIDER_PRIORITY_USER,
            );
            ACCENT_PROVIDER.with(|p| {
                if let Some(old_provider) = p.borrow_mut().take() {
                    gtk::style_context_remove_provider_for_display(&display, &old_provider);
                }
                *p.borrow_mut() = Some(new_provider);
            });
            crate::logging::log("[accent-css] provider reemplazado exitosamente");
        }
    }

    fn write_file_atomic(path: &std::path::Path, content: &str) {
        if let Some(parent) = path.parent() {
            let _ = fs::create_dir_all(parent);
        }
        let tmp = path.with_extension("tmp");
        if fs::write(&tmp, content).is_ok() {
            let _ = fs::rename(&tmp, path);
        }
    }

    fn write_accent_css(color_name: &str) {
        crate::logging::log(&format!("[accent] write_accent_css: {color_name}"));
        let path = Self::accent_css_path();
        let base = Self::hex_for(color_name);
        let css = Self::build_accent_css(&base, "churros set-accent");
        Self::write_file_atomic(&path, &css);
        let css_clone = css.clone();
        glib::idle_add_once(move || {
            crate::logging::log("[accent] ejecutando apply_css_to_provider (color_name)...");
            Self::apply_css_to_provider(&css_clone);
        });
    }

    pub fn set(color: &str) {
        settings::set("accent.color", serde_json::json!(color));
        Self::write_accent_css(color);
        // Si pywal está activo, el color con nombre se sobrescribe por la
        // paleta dinámica (paridad con accent.py del Python).
        if crate::services::pywal::PywalService::enabled() {
            if let Some(palette) = crate::services::pywal::PywalService::generate() {
                crate::services::pywal::PywalService::apply_accent(&palette);
            }
        }
    }

    /// Escribe accent.css con un hex arbitrario (para pywal). NO persiste en
    /// settings.json: el color custom se sobrescribe la próxima vez que el
    /// usuario elige un color con nombre.
    pub fn set_hex(hex: &str) {
        crate::logging::log(&format!("[accent] set_hex: {hex}"));
        let base = if hex.starts_with('#') {
            hex.to_string()
        } else {
            format!("#{hex}")
        };
        let path = Self::accent_css_path();
        let css = Self::build_accent_css(&base, "dynamic colors (pywal)");
        Self::write_file_atomic(&path, &css);
        let css_clone = css.clone();
        glib::idle_add_once(move || {
            crate::logging::log("[accent] ejecutando apply_css_to_provider (hex)...");
            Self::apply_css_to_provider(&css_clone);
        });
    }

    pub fn ensure() {
        let color = Self::current();
        if !Self::accent_css_path().exists() {
            Self::write_accent_css(&color);
        }
    }
}

fn hls_to_rgb(h: f64, l: f64, s: f64) -> (u8, u8, u8) {
    if s == 0.0 {
        let v = (l * 255.0).round() as u8;
        return (v, v, v);
    }
    let q = if l < 0.5 { l * (1.0 + s) } else { l + s - l * s };
    let p = 2.0 * l - q;
    let rgb = [
        hue_to_rgb(p, q, h + 1.0 / 3.0),
        hue_to_rgb(p, q, h),
        hue_to_rgb(p, q, h - 1.0 / 3.0),
    ];
    (
        (rgb[0] * 255.0).round() as u8,
        (rgb[1] * 255.0).round() as u8,
        (rgb[2] * 255.0).round() as u8,
    )
}

fn hue_to_rgb(p: f64, q: f64, mut t: f64) -> f64 {
    if t < 0.0 {
        t += 1.0;
    }
    if t > 1.0 {
        t -= 1.0;
    }
    if t < 1.0 / 6.0 {
        p + (q - p) * 6.0 * t
    } else if t < 1.0 / 2.0 {
        q
    } else if t < 2.0 / 3.0 {
        p + (q - p) * (2.0 / 3.0 - t) * 6.0
    } else {
        p
    }
}
