// ==========================================
// WaybarService — ~/.config/waybar/{config.jsonc, style.css, colors-waybar.css}
// ==========================================

use serde_json::{json, Value};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use churros_services::waybar_style;

pub struct WaybarService;

const DEFAULTS_DIR: &str = "/usr/share/churros/defaults/waybar";
const SKEL_DIR: &str = "/etc/skel/.config/waybar";

const EMBEDDED_CONFIG: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../archiso/airootfs/usr/share/churros/defaults/waybar/config.jsonc"
));
const EMBEDDED_STYLE: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../archiso/airootfs/usr/share/churros/defaults/waybar/style.css"
));
const EMBEDDED_COLORS: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../archiso/airootfs/usr/share/churros/defaults/waybar/colors-waybar.css"
));

fn home() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    PathBuf::from(home)
}

fn config_path() -> PathBuf {
    home().join(".config").join("waybar").join("config.jsonc")
}

fn style_path() -> PathBuf {
    home().join(".config").join("waybar").join("style.css")
}

fn colors_path() -> PathBuf {
    home()
        .join(".config")
        .join("waybar")
        .join("colors-waybar.css")
}

pub fn defaults() -> Value {
    json!({
        "layer": "top",
        "position": "top",
        "spacing": 0,
        "height": 30,
        "font-size": 14,
        "font-family": "JetBrainsMono Nerd Font",
        "background": "#2a1612",
        "foreground": "#c9c4c3",
        "accent": "#DE8636",
        "background-alpha": 0.9,
    })
}

/// Lee un JSONC. `None` = el archivo existe pero no se pudo leer o parsear.
/// `Some({})` = no hay archivo todavía (primera vez). Nunca se finge un
/// objeto vacío cuando el parseo falla: eso podía borrar la config al guardar.
fn read_jsonc(path: &Path) -> Option<Value> {
    if !path.exists() {
        return Some(json!({}));
    }
    let raw = fs::read_to_string(path).ok()?;
    churros_services::jsonc::parse(&raw).ok()
}

fn write_atomic(path: &Path, content: &str) -> bool {
    if let Some(parent) = path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    let tmp = path.with_extension("tmp");
    if fs::write(&tmp, content).is_err() {
        return false;
    }
    fs::rename(&tmp, path).is_ok()
}

fn write_jsonc(path: &Path, data: &Value) -> bool {
    let Ok(text) = serde_json::to_string_pretty(data) else {
        eprintln!("[waybar] no se pudo serializar config.jsonc");
        return false;
    };
    let content = format!(
        "// Auto-generated by churros-settings WaybarService\n\
         // Editalo desde Preferencias -> Waybar\n\
         {text}\n"
    );
    write_atomic(path, &content)
}

fn read_default_file(name: &str, embedded: &str) -> String {
    for dir in [DEFAULTS_DIR, SKEL_DIR] {
        let path = Path::new(dir).join(name);
        if let Ok(content) = fs::read_to_string(&path) {
            if !content.trim().is_empty() {
                return content;
            }
        }
    }
    embedded.to_string()
}

fn default_config() -> String {
    read_default_file("config.jsonc", EMBEDDED_CONFIG)
}

fn default_style() -> String {
    read_default_file("style.css", EMBEDDED_STYLE)
}

fn default_colors() -> String {
    read_default_file("colors-waybar.css", EMBEDDED_COLORS)
}

fn read_colors() -> Value {
    if !colors_path().exists() {
        return json!({});
    }
    let Ok(content) = fs::read_to_string(colors_path()) else {
        return json!({});
    };
    waybar_style::parse_define_colors(&content)
}

/// Lee style.css: font-family, font-size y background-alpha del bloque `*`.
fn read_style() -> Value {
    let mut result = json!({});
    if !style_path().exists() {
        return result;
    }
    let Ok(content) = fs::read_to_string(style_path()) else {
        return result;
    };

    let mut got_alpha = false;
    for line in content.lines() {
        let line = line.trim();
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        let key = key.trim();
        let value = value.trim().trim_end_matches(';').trim();

        match key {
            "font-family" => {
                if result.get("font-family").is_none() {
                    let v = value.trim_matches('\'');
                    result["font-family"] = json!(v);
                }
            }
            "font-size" => {
                if result.get("font-size").is_none() {
                    if let Some(px) = value.strip_suffix("px") {
                        if let Ok(n) = px.trim().parse::<i64>() {
                            result["font-size"] = json!(n);
                        }
                    }
                }
            }
            "background-color" => {
                if !got_alpha {
                    if let Some(inner) = value.strip_prefix("alpha(") {
                        let inner = inner.trim_end_matches(')');
                        if let Some((_, a)) = inner.rsplit_once(',') {
                            if let Ok(a) = a.trim().parse::<f64>() {
                                result["background-alpha"] = json!(a);
                                got_alpha = true;
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }
    result
}

fn colors_css(bg: &str, fg: &str, accent: &str) -> String {
    let bg = waybar_style::css_color(bg);
    let fg = waybar_style::css_color(fg);
    let accent = waybar_style::css_color(accent);
    format!(
        "@define-color background {bg};\n\
         @define-color foreground {fg};\n\
         @define-color color4 {accent};\n\
         @define-color color1 {accent};\n"
    )
}

fn write_colors(values: &Value) {
    let d = defaults();
    let bg = values
        .get("background")
        .and_then(|v| v.as_str())
        .unwrap_or(d["background"].as_str().unwrap());
    let fg = values
        .get("foreground")
        .and_then(|v| v.as_str())
        .unwrap_or(d["foreground"].as_str().unwrap());
    let accent = waybar_style::accent_hex(values)
        .unwrap_or_else(|| d["accent"].as_str().unwrap().to_string());
    let _ = write_atomic(&colors_path(), &colors_css(bg, fg, &accent));
}

/// Parchea font/alpha sobre el CSS actual. Si el archivo es el template
/// generado que tumbaba Waybar, se restaura el default del skel primero.
fn write_style(values: &Value) {
    let mut content = fs::read_to_string(style_path()).unwrap_or_default();
    if waybar_style::should_replace_style(&content) {
        content = default_style();
    }
    let d = defaults();
    let font_size = values
        .get("font-size")
        .and_then(|v| v.as_i64())
        .unwrap_or(d["font-size"].as_i64().unwrap());
    let font_family = values
        .get("font-family")
        .and_then(|v| v.as_str())
        .unwrap_or(d["font-family"].as_str().unwrap());
    let bg_alpha = values
        .get("background-alpha")
        .and_then(|v| v.as_f64())
        .unwrap_or(d["background-alpha"].as_f64().unwrap());
    let patched = waybar_style::patch_style(&content, font_family, font_size, bg_alpha);
    let _ = write_atomic(&style_path(), &patched);
}

fn uid() -> u32 {
    Command::new("id")
        .arg("-u")
        .output()
        .ok()
        .and_then(|o| String::from_utf8_lossy(&o.stdout).trim().parse().ok())
        .unwrap_or(0)
}

fn build_env() -> Vec<(String, String)> {
    let mut env: Vec<(String, String)> = std::env::vars().collect();

    let has_wayland = env.iter().any(|(k, _)| k == "WAYLAND_DISPLAY");
    if !has_wayland {
        let xrd =
            std::env::var("XDG_RUNTIME_DIR").unwrap_or_else(|_| format!("/run/user/{}", uid()));
        if std::path::Path::new(&xrd).is_dir() {
            if let Ok(entries) = fs::read_dir(&xrd) {
                let mut socks: Vec<String> = entries
                    .flatten()
                    .filter_map(|e| e.file_name().into_string().ok())
                    .filter(|n| n.starts_with("wayland-"))
                    .collect();
                socks.sort();
                if let Some(sock) = socks.first() {
                    if let Some(slot) = env.iter_mut().find(|(k, _)| k == "WAYLAND_DISPLAY") {
                        slot.1 = sock.clone();
                    } else {
                        env.push(("WAYLAND_DISPLAY".to_string(), sock.clone()));
                    }
                }
            }
        }
    }

    let has_xrd = env.iter().any(|(k, _)| k == "XDG_RUNTIME_DIR");
    if !has_xrd {
        env.push((
            "XDG_RUNTIME_DIR".to_string(),
            format!("/run/user/{}", uid()),
        ));
    }

    env
}

fn timestamp() -> String {
    Command::new("date")
        .args(["+%H:%M:%S"])
        .output()
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default()
}

fn waybar_running(env: &[(String, String)]) -> bool {
    Command::new("pgrep")
        .args(["-x", "waybar"])
        .envs(env.iter().cloned())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn signal_reload(env: &[(String, String)]) {
    let _ = Command::new("pkill")
        .args(["-x", "-USR2", "waybar"])
        .envs(env.iter().cloned())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();
}

fn spawn_waybar(env: &[(String, String)]) {
    if !churros_services::which("waybar") {
        return;
    }

    let mut cmd = Command::new("waybar");
    cmd.envs(env.iter().cloned());
    cmd.stdin(Stdio::null());
    use std::os::unix::process::CommandExt;
    cmd.process_group(0);

    match fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open("/tmp/waybar.log")
    {
        Ok(mut logf) => {
            let _ = writeln!(logf, "\n=== waybar reload {} ===\n", timestamp());
            let _ = logf.flush();
            match logf.try_clone() {
                Ok(clone) => {
                    cmd.stdout(Stdio::from(clone));
                    cmd.stderr(Stdio::from(logf));
                }
                Err(_) => {
                    cmd.stdout(Stdio::null());
                    cmd.stderr(Stdio::null());
                }
            }
        }
        Err(_) => {
            cmd.stdout(Stdio::null());
            cmd.stderr(Stdio::null());
        }
    }

    let _ = cmd.spawn();
}

impl WaybarService {
    pub fn config_path() -> PathBuf {
        config_path()
    }

    pub fn style_path() -> PathBuf {
        style_path()
    }

    pub fn colors_path() -> PathBuf {
        colors_path()
    }

    pub fn defaults() -> Value {
        defaults()
    }

    /// Lee config.jsonc + colors-waybar.css + style.css y devuelve el estado completo.
    pub fn get() -> Value {
        let cfg = read_jsonc(&config_path()).unwrap_or_else(|| json!({}));
        let colors = read_colors();
        let style = read_style();

        let d = defaults();
        let accent = waybar_style::accent_hex(&colors)
            .unwrap_or_else(|| d["accent"].as_str().unwrap().to_string());
        json!({
            "layer": cfg.get("layer").and_then(|v| v.as_str()).unwrap_or(d["layer"].as_str().unwrap()).to_string(),
            "position": cfg.get("position").and_then(|v| v.as_str()).unwrap_or(d["position"].as_str().unwrap()).to_string(),
            "spacing": cfg.get("spacing").and_then(|v| v.as_i64()).unwrap_or(d["spacing"].as_i64().unwrap()),
            "height": cfg.get("height").and_then(|v| v.as_i64()).unwrap_or(d["height"].as_i64().unwrap()),
            "font-size": style.get("font-size").and_then(|v| v.as_i64()).unwrap_or(d["font-size"].as_i64().unwrap()),
            "font-family": style.get("font-family").and_then(|v| v.as_str()).unwrap_or(d["font-family"].as_str().unwrap()).to_string(),
            "background": colors.get("background").and_then(|v| v.as_str()).unwrap_or(d["background"].as_str().unwrap()).to_string(),
            "foreground": colors.get("foreground").and_then(|v| v.as_str()).unwrap_or(d["foreground"].as_str().unwrap()).to_string(),
            "accent": accent,
            "background-alpha": style.get("background-alpha").and_then(|v| v.as_f64()).unwrap_or(d["background-alpha"].as_f64().unwrap()),
            "modules-left": cfg.get("modules-left").cloned().unwrap_or_else(|| json!([])),
            "modules-center": cfg.get("modules-center").cloned().unwrap_or_else(|| json!([])),
            "modules-right": cfg.get("modules-right").cloned().unwrap_or_else(|| json!([])),
        })
    }

    /// Escribe config.jsonc (conservando el resto de claves: módulos custom,
    /// group/tray-expander, etc.) y parchea colors + style. No recarga.
    pub fn set(values: &Value) {
        let d = defaults();
        let Some(mut cfg) = read_jsonc(&config_path()) else {
            eprintln!("[waybar] config.jsonc ilegible; no se sobrescribe");
            return;
        };

        if cfg.as_object().map(|o| o.is_empty()).unwrap_or(true) {
            if let Ok(parsed) = churros_services::jsonc::parse(&default_config()) {
                cfg = parsed;
            }
        }

        let layer = values
            .get("layer")
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty())
            .unwrap_or(d["layer"].as_str().unwrap());
        let position = values
            .get("position")
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty())
            .unwrap_or(d["position"].as_str().unwrap());

        cfg["layer"] = json!(layer);
        cfg["position"] = json!(position);
        cfg["spacing"] = json!(values
            .get("spacing")
            .and_then(|v| v.as_i64())
            .unwrap_or(d["spacing"].as_i64().unwrap()));
        cfg["height"] = json!(values
            .get("height")
            .and_then(|v| v.as_i64())
            .unwrap_or(d["height"].as_i64().unwrap()));

        for key in ["modules-left", "modules-center", "modules-right"] {
            if let Some(modules) = values.get(key) {
                cfg[key] = modules.clone();
            }
        }

        if !write_jsonc(&config_path(), &cfg) {
            return;
        }
        write_colors(values);
        write_style(values);
    }

    /// Aplica una paleta pywal a waybar (colors-waybar.css) y recarga.
    /// Solo toca los colores, sin pisar config.jsonc/style.css.
    pub fn apply_pywal_colors(bg: &str, fg: &str, accent: &str) {
        let _ = write_atomic(&colors_path(), &colors_css(bg, fg, accent));
        Self::reload(false);
    }

    /// Recarga in-place con SIGUSR2. Solo relanza el proceso si no hay barra.
    /// Matar y respawnear era lo que dejaba la barra muerta si el spawn fallaba
    /// (p.ej. al no poder abrir /tmp/waybar.log).
    pub fn reload(_full_restart: bool) {
        let env = build_env();
        if waybar_running(&env) {
            signal_reload(&env);
            return;
        }
        spawn_waybar(&env);
    }

    /// Restaura config/style/colors desde los defaults de ChurrOS y recarga.
    pub fn reset() {
        let dest = home().join(".config").join("waybar");
        let _ = fs::create_dir_all(&dest);
        let _ = write_atomic(&dest.join("config.jsonc"), &default_config());
        let _ = write_atomic(&dest.join("style.css"), &default_style());
        let _ = write_atomic(&dest.join("colors-waybar.css"), &default_colors());
        Self::reload(false);
    }
}
