// ==========================================
// WaybarService — ~/.config/waybar/{config.jsonc, style.css, colors-waybar.css}
// (equivalente a services/waybar.py)
// ==========================================

use serde_json::{json, Value};
use std::fs;
use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::time::Duration;

pub struct WaybarService;

fn home() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    PathBuf::from(home)
}

fn config_path() -> PathBuf {
    home().join(".config").join("waybar").join("config.jsonc")
}

fn style_path() -> PathBuf {
    home().join(".config").join("waybar").join("style.css")
}

fn colors_path() -> PathBuf {
    home().join(".config").join("waybar").join("colors-waybar.css")
}

pub fn defaults() -> Value {
    json!({
        "layer": "top",
        "position": "top",
        "spacing": 0,
        "height": 30,
        "font-size": 14,
        "font-family": "JetBrainsMono Nerd Font",
        "background": "#2a1612",
        "foreground": "#c9c4c3",
        "accent": "#DE8636",
        "background-alpha": 0.9,
    })
}

/// Lee un JSONC. `None` = el archivo existe pero no se pudo leer o parsear.
/// `Some({})` = no hay archivo todavía (primera vez). Nunca se finge un
/// objeto vacío cuando el parseo falla: eso podía borrar la config al guardar.
fn read_jsonc(path: &PathBuf) -> Option<Value> {
    if !path.exists() {
        return Some(json!({}));
    }
    let raw = fs::read_to_string(path).ok()?;
    churros_services::jsonc::parse(&raw).ok()
}

fn write_jsonc(path: &PathBuf, data: &Value) {
    if let Some(parent) = path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    let text = serde_json::to_string_pretty(data).unwrap_or_default();
    let content = format!(
        "// Auto-generated by churros-settings WaybarService\n\
         // Editalo desde Preferencias -> Waybar\n\
         {text}"
    );
    let _ = fs::write(path, content);
}

/// Lee colors-waybar.css: líneas "@define-color nombre valor;"
fn read_colors() -> Value {
    let mut result = json!({});
    if !colors_path().exists() {
        return result;
    }
    let Ok(content) = fs::read_to_string(colors_path()) else {
        return result;
    };
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with("@import") || line.starts_with("/*") {
            continue;
        }
        if line.starts_with("@define-color") {
            let parts: Vec<&str> = line.splitn(3, char::is_whitespace).collect();
            if parts.len() >= 3 {
                let name = parts[1].trim_start_matches('@');
                let value = parts[2].trim_end_matches(';');
                if let Some(obj) = result.as_object_mut() {
                    obj.insert(name.to_string(), json!(value));
                }
            }
        }
    }
    result
}

/// Lee style.css: font-family, font-size y background-alpha del bloque `*`
/// (font-size/font-family/background-alpha se persisten en style.css, no en
/// colors-waybar.css; leerlos de los colores los perdía siempre).
fn read_style() -> Value {
    let mut result = json!({});
    if !style_path().exists() {
        return result;
    }
    let Ok(content) = fs::read_to_string(style_path()) else {
        return result;
    };

    let mut got_alpha = false;
    for line in content.lines() {
        let line = line.trim();
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        let key = key.trim();
        let value = value.trim().trim_end_matches(';').trim();

        match key {
            "font-family" => {
                if result.get("font-family").is_none() {
                    let v = value.trim_matches('\'');
                    result["font-family"] = json!(v);
                }
            }
            "font-size" => {
                if result.get("font-size").is_none() {
                    if let Some(px) = value.strip_suffix("px") {
                        if let Ok(n) = px.trim().parse::<i64>() {
                            result["font-size"] = json!(n);
                        }
                    }
                }
            }
            "background-color" => {
                // Solo el primer alpha(...): el del bloque `*`; el resto del
                // archivo (tooltip, workspaces, mpris) usa alphas derivados.
                if !got_alpha {
                    if let Some(inner) = value.strip_prefix("alpha(") {
                        let inner = inner.trim_end_matches(')');
                        if let Some((_, a)) = inner.rsplit_once(',') {
                            if let Ok(a) = a.trim().parse::<f64>() {
                                result["background-alpha"] = json!(a);
                                got_alpha = true;
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }
    result
}

fn write_colors(values: &Value) {
    if let Some(parent) = colors_path().parent() {
        let _ = fs::create_dir_all(parent);
    }
    let bg = values.get("background").and_then(|v| v.as_str()).unwrap_or("#2a1612");
    let fg = values.get("foreground").and_then(|v| v.as_str()).unwrap_or("#c9c4c3");
    let accent = values.get("accent").and_then(|v| v.as_str()).unwrap_or("#DE8636");
    let content = colors_css(bg, fg, accent);
    let _ = fs::write(colors_path(), content);
}

fn colors_css(bg: &str, fg: &str, accent: &str) -> String {
    format!(
        "@define-color background {bg};\n\
         @define-color foreground {fg};\n\
         @define-color color4 {accent};\n\
         @define-color color1 {accent};\n"
    )
}

fn write_style(values: &Value) {
    if let Some(parent) = style_path().parent() {
        let _ = fs::create_dir_all(parent);
    }
    let font_size = values
        .get("font-size")
        .and_then(|v| v.as_i64())
        .unwrap_or(14);
    let font_family = values
        .get("font-family")
        .and_then(|v| v.as_str())
        .unwrap_or("JetBrainsMono Nerd Font");
    let bg_alpha = values
        .get("background-alpha")
        .and_then(|v| v.as_f64())
        .unwrap_or(0.9);

    let css = format!(
        "/* ChurrOS Waybar — Liquid Glass   (auto-generated) */\n\
\n\
@import \"./colors-waybar.css\";\n\
\n\
* {{\n\
    background-color: alpha(@background, {bg_alpha:.2});\n\
    color: @foreground;\n\
    border: none;\n\
    border-radius: 0;\n\
    min-height: 0;\n\
    font-family: '{font_family}';\n\
    font-size: {font_size}px;\n\
    border: 0px solid alpha(@foreground, 0.6);\n\
}}\n\
\n\
window#waybar {{\n\
    background-color: transparent;\n\
    color: @foreground;\n\
}}\n\
\n\
.modules-left {{\n\
    margin-left: 5px;\n\
}}\n\
\n\
.modules-right {{\n\
    margin-right: 5px;\n\
}}\n\
\n\
#workspaces {{\n\
    padding: 0 4px;\n\
    margin: 4px 4px;\n\
    border-radius: 12px;\n\
    background-color: alpha(@background, {workspaces_alpha:.2});\n\
    border: 1px solid alpha(@foreground, 0.06);\n\
}}\n\
\n\
#workspaces button {{\n\
    all: initial;\n\
    padding: 0 6px;\n\
    margin: 2px 1px;\n\
    min-width: 9px;\n\
    border-radius: 6px;\n\
    color: alpha(@foreground, 0.5);\n\
}}\n\
\n\
#workspaces button.empty {{\n\
    opacity: 0.45;\n\
}}\n\
\n\
#workspaces button.active,\n\
#workspaces button.focused {{\n\
    background-color: alpha(@color4, 0.30);\n\
    color: @foreground;\n\
}}\n\
\n\
#workspaces button:hover {{\n\
    background-color: alpha(@color4, 0.12);\n\
}}\n\
\n\
#cpu,\n\
#idle_inhibitor,\n\
#battery,\n\
#custom-screenrecording-indicator,\n\
#custom-dnd {{\n\
    min-width: 10px;\n\
    margin: 0 7.5px;\n\
}}\n\
\n\
#custom-launcher {{\n\
    margin-left: 2px;\n\
    margin-right: 8px;\n\
    background-color: alpha(@color4, 0.20);\n\
    padding: 4px 10px;\n\
    border-radius: 10px;\n\
    color: @color4;\n\
}}\n\
\n\
#custom-launcher:hover {{\n\
    background-color: alpha(@color4, 0.35);\n\
}}\n\
\n\
#pulseaudio {{\n\
    margin-right: 4px;\n\
    margin-left: 1px;\n\
}}\n\
\n\
#tray {{\n\
    margin-right: 4px;\n\
}}\n\
\n\
#bluetooth {{\n\
    margin-right: 2px;\n\
}}\n\
\n\
#network {{\n\
    margin-right: 10px;\n\
    margin-left: 6px;\n\
}}\n\
\n\
#custom-expand-icon {{\n\
    margin-right: 10px;\n\
}}\n\
\n\
tooltip {{\n\
    padding: 4px 8px;\n\
    border-radius: 8px;\n\
    background-color: alpha(@background, 0.90);\n\
    border: 1px solid alpha(@foreground, 0.08);\n\
}}\n\
\n\
#clock {{\n\
    margin-left: 8px;\n\
    font-weight: 600;\n\
}}\n\
\n\
.hidden {{\n\
    opacity: 0;\n\
}}\n\
\n\
#custom-screenrecording-indicator {{\n\
    min-width: 12px;\n\
    margin-left: 8px;\n\
    font-size: 10px;\n\
}}\n\
\n\
#custom-screenrecording-indicator.active {{\n\
    color: #a55555;\n\
}}\n\
\n\
#custom-dnd.active {{\n\
    color: @color4;\n\
}}\n\
\n\
#mpris {{\n\
    font-weight: 600;\n\
    border-radius: 14px;\n\
    padding: 2px 8px;\n\
    margin: 2px 2px;\n\
    background-color: alpha(@background, {mpris_alpha:.2});\n\
}}\n\
\n\
#memory,\n\
#disk,\n\
#cpu,\n\
#battery,\n\
#backlight,\n\
#network,\n\
#bluetooth,\n\
#pulseaudio,\n\
#idle_inhibitor,\n\
#custom-dnd {{\n\
    padding: 0 4px;\n\
    border-radius: 8px;\n\
}}\n\
\n\
#memory:hover,\n\
#disk:hover,\n\
#cpu:hover,\n\
#battery:hover,\n\
#backlight:hover,\n\
#network:hover,\n\
#bluetooth:hover,\n\
#pulseaudio:hover,\n\
#idle_inhibitor:hover,\n\
#custom-dnd:hover {{\n\
    background-color: alpha(@color4, 0.12);\n\
}}\n\
\n\
#battery.warning {{\n\
    color: #f59e0b;\n\
}}\n\
\n\
#battery.critical {{\n\
    color: #ef4444;\n\
}}\n\
\n\
#battery.charging {{\n\
    color: @color4;\n\
}}\n\
\n\
#custom/sep {{\n\
    color: alpha(@foreground, 0.20);\n\
    margin: 0 4px;\n\
}}\n",
        bg_alpha = bg_alpha,
        workspaces_alpha = (bg_alpha - 0.2).max(0.0),
        mpris_alpha = (bg_alpha - 0.2).max(0.0),
    );
    let _ = fs::write(style_path(), css);
}

/// uid numérico (como os.getuid())
fn uid() -> u32 {
    Command::new("id")
        .arg("-u")
        .output()
        .ok()
        .and_then(|o| String::from_utf8_lossy(&o.stdout).trim().parse().ok())
        .unwrap_or(0)
}

/// Entorno para lanzar waybar: asegura WAYLAND_DISPLAY y XDG_RUNTIME_DIR
/// (equivalente a _build_env)
fn build_env() -> Vec<(String, String)> {
    let mut env: Vec<(String, String)> = std::env::vars().collect();

    let has_wayland = env.iter().any(|(k, _)| k == "WAYLAND_DISPLAY");
    if !has_wayland {
        let xrd = std::env::var("XDG_RUNTIME_DIR")
            .unwrap_or_else(|_| format!("/run/user/{}", uid()));
        if std::path::Path::new(&xrd).is_dir() {
            if let Ok(entries) = fs::read_dir(&xrd) {
                let mut socks: Vec<String> = entries
                    .flatten()
                    .filter_map(|e| e.file_name().into_string().ok())
                    .filter(|n| n.starts_with("wayland-"))
                    .collect();
                socks.sort();
                if let Some(sock) = socks.first() {
                    if let Some(slot) = env.iter_mut().find(|(k, _)| k == "WAYLAND_DISPLAY") {
                        slot.1 = sock.clone();
                    } else {
                        env.push(("WAYLAND_DISPLAY".to_string(), sock.clone()));
                    }
                }
            }
        }
    }

    let has_xrd = env.iter().any(|(k, _)| k == "XDG_RUNTIME_DIR");
    if !has_xrd {
        env.push(("XDG_RUNTIME_DIR".to_string(), format!("/run/user/{}", uid())));
    }

    env
}

/// ¿Existe el binario en PATH? (como shutil.which)
fn which(bin: &str) -> bool {
    Command::new("sh")
        .args(["-c", &format!("command -v {bin} >/dev/null 2>&1")])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn timestamp() -> String {
    Command::new("date")
        .args(["+%H:%M:%S"])
        .output()
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default()
}

impl WaybarService {
    pub fn config_path() -> PathBuf {
        config_path()
    }

    pub fn style_path() -> PathBuf {
        style_path()
    }

    pub fn colors_path() -> PathBuf {
        colors_path()
    }

    pub fn defaults() -> Value {
        defaults()
    }

    /// Lee config.jsonc + colors-waybar.css + style.css y devuelve el estado completo.
    pub fn get() -> Value {
        let cfg = read_jsonc(&config_path()).unwrap_or_else(|| json!({}));
        let colors = read_colors();
        let style = read_style();

        let d = defaults();
        json!({
            "layer": cfg.get("layer").and_then(|v| v.as_str()).unwrap_or(d["layer"].as_str().unwrap()).to_string(),
            "position": cfg.get("position").and_then(|v| v.as_str()).unwrap_or(d["position"].as_str().unwrap()).to_string(),
            "spacing": cfg.get("spacing").and_then(|v| v.as_i64()).unwrap_or(d["spacing"].as_i64().unwrap()),
            "height": cfg.get("height").and_then(|v| v.as_i64()).unwrap_or(d["height"].as_i64().unwrap()),
            "font-size": style.get("font-size").and_then(|v| v.as_i64()).unwrap_or(d["font-size"].as_i64().unwrap()),
            "font-family": style.get("font-family").and_then(|v| v.as_str()).unwrap_or(d["font-family"].as_str().unwrap()).to_string(),
            "background": colors.get("background").and_then(|v| v.as_str()).unwrap_or(d["background"].as_str().unwrap()).to_string(),
            "foreground": colors.get("foreground").and_then(|v| v.as_str()).unwrap_or(d["foreground"].as_str().unwrap()).to_string(),
            "accent": colors.get("accent").and_then(|v| v.as_str()).unwrap_or(d["accent"].as_str().unwrap()).to_string(),
            "background-alpha": style.get("background-alpha").and_then(|v| v.as_f64()).unwrap_or(d["background-alpha"].as_f64().unwrap()),
            "modules-left": cfg.get("modules-left").cloned().unwrap_or_else(|| json!([])),
            "modules-center": cfg.get("modules-center").cloned().unwrap_or_else(|| json!([])),
            "modules-right": cfg.get("modules-right").cloned().unwrap_or_else(|| json!([])),
        })
    }

    /// Escribe config.jsonc + colors + style. NO recarga waybar
    /// (el usuario debe pulsar "Guardar y aplicar"; recargar con SIGUSR2
    /// hace que waybar desaparezca temporalmente y en algunas builds la mata).
    pub fn set(values: &Value) {
        let d = defaults();
        let Some(mut cfg) = read_jsonc(&config_path()) else {
            eprintln!("[waybar] config.jsonc ilegible; no se sobrescribe");
            return;
        };

        cfg["layer"] = values
            .get("layer")
            .cloned()
            .unwrap_or_else(|| d["layer"].clone());
        cfg["position"] = values
            .get("position")
            .cloned()
            .unwrap_or_else(|| d["position"].clone());
        cfg["spacing"] = json!(values
            .get("spacing")
            .and_then(|v| v.as_i64())
            .unwrap_or(d["spacing"].as_i64().unwrap()));
        cfg["height"] = json!(values
            .get("height")
            .and_then(|v| v.as_i64())
            .unwrap_or(d["height"].as_i64().unwrap()));

        for key in ["modules-left", "modules-center", "modules-right"] {
            if let Some(modules) = values.get(key) {
                cfg[key] = modules.clone();
            }
        }

        write_jsonc(&config_path(), &cfg);
        write_colors(values);
        write_style(values);
    }

    /// Aplica una paleta pywal a waybar (colors-waybar.css) y recarga.
    /// Solo toca los colores, sin pisar config.jsonc/style.css.
    pub fn apply_pywal_colors(bg: &str, fg: &str, accent: &str) {
        if let Some(parent) = colors_path().parent() {
            let _ = fs::create_dir_all(parent);
        }
        let _ = fs::write(colors_path(), colors_css(bg, fg, accent));

        // Recargar waybar con SIGUSR2 (recarga la config en vivo)
        let env = build_env();
        let _ = Command::new("pkill")
            .args(["-SIGUSR2", "waybar"])
            .envs(env.iter().cloned())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }

    /// Mata waybar limpiamente y lo relanza (equivalente a reload()).
    pub fn reload(_full_restart: bool) {
        let env = build_env();

        // pkill -x waybar (espera)
        let _ = Command::new("pkill")
            .args(["-x", "waybar"])
            .envs(env.iter().cloned())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();

        std::thread::sleep(Duration::from_millis(500));

        // Verificar que no queden procesos
        let running = Command::new("pgrep")
            .args(["-x", "waybar"])
            .envs(env.iter().cloned())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .map(|s| s.success())
            .unwrap_or(false);

        if running {
            let _ = Command::new("pkill")
                .args(["-9", "-x", "waybar"])
                .envs(env.iter().cloned())
                .stdout(Stdio::null())
                .stderr(Stdio::null())
                .status();
            std::thread::sleep(Duration::from_millis(300));
        }

        if !which("waybar") {
            return;
        }

        let log_path = "/tmp/waybar.log";
        if let Ok(mut logf) = fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(log_path)
        {
            let _ = writeln!(logf, "\n=== waybar reload {} ===\n", timestamp());
            let _ = logf.flush();

            let stdout = Stdio::from(logf.try_clone().unwrap_or_else(|_| logf.try_clone().expect("log")));
            let stderr = Stdio::from(logf);

            let mut cmd = Command::new("waybar");
            cmd.envs(env.iter().cloned());
            cmd.stdout(stdout);
            cmd.stderr(stderr);
            // start_new_session=True (grupo propio)
            use std::os::unix::process::CommandExt;
            cmd.process_group(0);
            let _ = cmd.spawn();
        }
    }

    /// Borra los tres archivos de config de waybar (equivalente a reset()).
    pub fn reset() {
        for p in [config_path(), style_path(), colors_path()] {
            if p.exists() {
                let _ = fs::remove_file(p);
            }
        }
    }
}
