---
unpack:
  - source: "/run/archiso/bootmnt/churros/i686/airootfs.sfs"
    sourcefs: "squashfs"
    destination: ""
    weight: 12
  - source: "/run/archiso/bootmnt/churros/boot/i686/vmlinuz-linux"
    sourcefs: "file"
    destination: "/boot/vmlinuz-linux"
  - source: "/run/archiso/bootmnt/churros/boot/i686/initramfs-linux.img"
    sourcefs: "file"
    destination: "/boot/initramfs-linux.img"
